yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('new/', views.new_post, name='new_post'),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view, name='post'),
    path('<str:username>/<int:post_id>/edit',
         views.post_edit,
         name='post_edit'),
]

yatube/users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup')
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("posts.urls")),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about'))
]

yatube/about/models.py
from django.db import models

# Create your models here.

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models


User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название группы')
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return(self.title)


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField("date published", auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="posts")
    group = models.ForeignKey("Group", on_delete=models.SET_NULL,
                              blank=True, null=True, name='group')

    def __str__(self):
        return(self.text)

yatube/users/models.py
from django.db import models

# Create your models here.

yatube/posts/forms.py
from django.forms import ModelForm, widgets

from .models import Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group')
        widgets = {
            'text': widgets.Textarea(attrs={
                'class': 'form_control',
                'placeholder': 'Текст поста'
            })
        }

yatube/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

yatube/about/views.py
from django.views.generic.base import TemplateView


class AboutAuthorView(TemplateView):
    template_name = 'about/author.html'


class AboutTechView(TemplateView):
    template_name = 'about/tech.html'

# Create your views here.

yatube/posts/views.py
from .forms import PostForm
from django.shortcuts import get_object_or_404, redirect, render
from .models import Group, Post, User
from django.core.paginator import Paginator


def index(request):
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {"page": page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "posts/group.html", {"group": group, "page": page})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author=author).order_by('-pub_date')
    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'profile.html', {"author": author, "page": page})


def post_view(request, username, post_id):
    author = get_object_or_404(User, username=username)
    post = Post.objects.filter(author=author).get(id=post_id)
    return render(request, 'post.html', {"author": author, "post": post})


def new_post(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        form.save()
        return redirect('index')
    form = PostForm()
    return render(request, 'new_post.html', {'form': form})


def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('post', username, post_id)
    form = PostForm(request.POST or None, instance=post)
    if form.is_valid():
        form.save()
        return redirect('post', username, post_id)
    form = PostForm()
    return render(request, 'new_post.html', {'form': form,
                                             'edit': True})

yatube/users/views.py
from django.views.generic import CreateView

from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

yatube/posts/templates/posts/group.html
{% extends 'base.html' %}
{% block title %} Записи сообщества {{ group.title }} {% endblock %}
{% block header %}{{group.title}}{% endblock %}
{% block content %}

<h1>{{group.title}}</h1>
<p>{{ group.description }}</p>

{% for post in page %}
<h3>
    Автор: {{ post.author.get_full_name }},
    Дата публикации: {{ post.pub_date|date:"d M Y" }}
</h3>

<p>{{ post.text|linebreaksbr }}</p>

{% if not forloop.last %}
<hr>{% endif %}

{% endfor %}

{% include "paginator.html" %}

{% endblock %}

yatube/templates/about/author.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Об авторе проекта{% endblock %}
{% block content %}
  <div class="row">
    <!-- Левый вспомогательный блок -->
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Об авторе
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Полезный короткий текст
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Тело страницы -->
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Текст страницы "Об авторе"</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/about/tech.html
<!-- templates/about/author.html -->
{% extends "base.html" %}
{% block title %}Технологии проекта{% endblock %}
{% block content %}
  <div class="row">
    <!-- Левый вспомогательный блок -->
    <div class="col-md-3 mb-3 mt-1">
      <div class="card">
        <div class="card-body">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="h3">
                Технологии
              </div>
            </li>
            <li class="list-group-item">
              <div class="h6 text-muted">
                Полезный короткий текст
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <!-- Тело страницы -->
    <div class="col-md-9">
      <div class="card-body">
        <div class="card-text">
          <p>Текст страницы "Технологии"</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

yatube/templates/base.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </head>
  <body>
    {% include 'nav.html' %}
    <main>
      <div class="container" >
        {% block content %}
        <!-- Содержимое страницы -->
        {% endblock content %}
      </div>
    </main>
    {% include 'footer.html' %}
    </body>
</html>

yatube/templates/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
        Социальная сеть <span style="color:red">Ya</span>tube © 2021, все права защищены.</p>
</footer>

yatube/templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}

  {% for post in page %}
    <h3>
        Автор: <a class="p-2 text-dark" href="{% url 'profile' post.author.username %}">{{ post.author.get_full_name }}</a>, Дата публикации: {{ post.pub_date|date:"d M Y" }}
    </h3>
    <p>{{ post.text|linebreaksbr }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}

 {% include "paginator.html" %}
 
{% endblock %}

yatube/templates/nav.html
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="/"><span style="color:red">Ya</span>tube</a>
    
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}
      Пользователь: <a class="p-2 text-dark" href="{% url 'profile' user.username %}">{{ user.username }}.</a>
      <a class="p-2 text-dark" href="{% url 'new_post' %}">Новая запись</a>
      <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
      <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
      {% else %}
      <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
      <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
      {% endif %}
    </nav>
  </nav>

yatube/templates/new_post.html
{% extends 'base.html' %}

{% block title %}

{% if edit%}
Редактирование поста
{%else%}
Новый пост
{%endif%}
{% endblock %}


{%block content%}

<form method="post">
  {% csrf_token %}
  {{ form.as_table }}
  {% if edit%}
  <input type="submit" value="Сохранить">
  {%else%}
  <input type="submit" value="Добавить">
  {%endif%}
 
</form>

{% endblock %}

yatube/templates/paginator.html
    {% if page.has_other_pages %}
      <nav>
        <ul class="pagination">
          {% if page.has_previous %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">&laquo; Предыдущая</span>
            </li>
          {% endif %}
          {% for i in page.paginator.page_range %}
            {% if page.number == i %}
              <li class="page-item active">
                <span class="page-link">{{ i }}
                  <span class="sr-only">(текущая)</span>
                </span>
              </li>
            {% else %}
              <li class="page-item">
                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
              </li>
            {% endif %}
          {% endfor %}
          {% if page.has_next %}
            <li class="page-item">
              <a
                class="page-link"
                href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
            </li>
          {% else %}
            <li class="page-item disabled">
              <span class="page-link">Следующая &raquo;</span>
            </li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}

yatube/templates/post.html
{% extends 'base.html' %} 
{% block content %} 
<main role="main" class="container"> 
    <div class="row"> 
      <div class="col-md-3 mb-3 mt-1"> 
        <div class="card"> 
          <div class="card-body"> 
            <div class="h2"> 
              <!-- Имя автора --> 
              {{ author.get_full_name }} 
            </div> 
            <div class="h3 text-muted"> 
              <!-- username автора --> 
               {{ author.username }} 
            </div> 
          </div> 
          <ul class="list-group list-group-flush"> 
            <li class="list-group-item"> 
              <div class="h6 text-muted"> 
                Подписчиков: XXX <br /> 
                Подписан: XXX 
              </div> 
            </li> 
            <li class="list-group-item"> 
              <div class="h6 text-muted"> 
                <!--Количество записей --> 
                {{ count }} 
              </div> 
            </li> 
          </ul> 
        </div> 
      </div> 
      <div class="col-md-9"> 
      <!-- Пост --> 
        <div class="card mb-3 mt-1 shadow-sm"> 
          <div class="card-body"> 
            <p class="card-text"> 
              <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки --> 
              <a href="/{{ post.author.username }}/"> 
                <strong class="d-block text-gray-dark"> 
                  {{ author.username }} 
                </strong> 
              </a> 
              <!-- Текст поста --> 
              {{ post }} 
            </p> 
            <div class="d-flex justify-content-between align-items-center"> 
              <div class="btn-group"> 
                <!-- Ссылка на редактирование, показывается только автору записи. 
                Эту ссылку вы подключите в финальном задании спринта --> 
                {% if user.username == post.author.username  %} 
                <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{ post.id }}/edit" role="button"> 
                  Редактировать 
                </a> 
                {% endif %} 
              </div> 
              <!-- Дата публикации  --> 
              <small class="text-muted">{{ post.pub_date }}</small> 
            </div> 
          </div> 
        </div> 
      </div> 
    </div> 
  </main> 
{% endblock %} 

yatube/templates/profile.html
{% extends 'base.html' %} 
{% block content %} 
<main role="main" class="container"> 
    <div class="row"> 
      <div class="col-md-3 mb-3 mt-1"> 
        <div class="card"> 
          <div class="card-body"> 
            <div class="h2"> 
               {{ author.get_full_name }} 
            </div> 
            <div class="h3 text-muted"> 
               {{ author.username }} 
             </div> 
           </div> 
           <ul class="list-group list-group-flush"> 
             <li class="list-group-item"> 
               <div class="h6 text-muted"> 
                 Подписчиков: XXX <br /> 
                 Подписан: XXX 
                </div> 
             </li> 
             <li class="list-group-item"> 
                <div class="h6 text-muted"> 
                  Записей: {{ count }} 
                 </div> 
              </li> 
            </ul> 
          </div> 
       </div> 
   
       <div class="col-md-9"> 
         {% for post in page %} 
          <div class="card mb-3 mt-1 shadow-sm"> 
            <div class="card-body"> 
              <p class="card-text"> 
                <a href="/{{ post.author.username }}/"> 
                  <strong class="d-block text-gray-dark">{{ post.author.username }}</strong> 
                </a> 
                {{ post }} 
              </p> 
              <div class="d-flex justify-content-between align-items-center"> 
                <div class="btn-group "> 
                  <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{ post.id }}/" role="button"> 
                    Добавить комментарий 
                  </a> 
                  {% if user.username == post.author.username  %} 
                  <a class="btn btn-sm text-muted" href="/{{ post.author.username }}/{{ post.id }}/edit" role="button"> 
                    Редактировать 
                  </a> 
                  {% endif %} 
                 </div> 
                  <small class="text-muted">{{ post.pub_date }}</small> 
              </div> 
            </div> 
          </div> 
          {% endfor %} 
           
          {% include "paginator.html" %} 
       </div> 
    </div> 
  </main> 
{% endblock %}  

yatube/users/templates/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
{%load user_filters%}

  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">Зарегистрироваться</div>
        <div class="card-body">

          {% for error in form.errors %}
            <div class="alert alert-danger" role="alert">
              {{ error }}
            </div>
          {% endfor %}

          <form method="post" action="{% url 'signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row" aria-required={{ field.field.required }}>
                <label
                  for="{{ field.id_for_label }}"
                  class="col-md-4 col-form-label text-md-right">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required">*</span>
                  {% endif %}
                </label>
                <div class="col-md-6">
                 <!--{{ field }}--> 
                 {{field|addclass:"form-control"}}
                  {% if field.help_text %}
                    <small
                      id="{{ field.id_for_label }}-help"
                      class="form-text text-muted">
                      {{ field.help_text|safe }}
                    </small>
                  {% endif %}
                </div>
              </div>
            {% endfor %}

            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div> <!-- card body -->
      </div> <!-- card -->
    </div> <!-- col -->
  </div> <!-- row -->

{% endblock %}